<<<<<<< HEAD
services:
  web:
    build:
      context: ./BlogApp.Web
=======
version: '3.9'

services:
  web:
    build:
      context: ./BlogApp.web
>>>>>>> fe9a7f3c8525618470b78ae131c47c5f1c762dad
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      ASPNETCORE_URLS: "http://+:8080;https://+:8443"
      ConnectionStrings__BlogConnection: Server=db;Database=BlogDb;User ID=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;
      Admin__Key: ${ADMIN_KEY}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: