name: CD - Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo 'SA_PASSWORD=${{ secrets.SA_PASSWORD }}' > .env
          echo 'ADMIN_KEY=${{ secrets.ADMIN_KEY }}' >> .env

      - name: Build container
        run: docker compose build 

      - name: Run containers detached & cleanup old images
        run: docker compose up -d && docker image prune -f